config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  get 'home/about' => 'homes#about'
  get "search" => "searches#search"


  resources :users, only: [:show, :edit, :update, :index]
  resources :books, only: [:create, :index, :show, :destroy, :edit, :updatey] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
    end

  resources :users, only:[:index, :show, :edit, :update] do
  member do
  get :follows, :followers
      end
  resource :relationships, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
     belongs_to :user
     belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
    user_path(current_user.id)
   end

   def after_sign_out_path_for(resource)
    root_path
   end

   private

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
   end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

def create
   book = Book.find(params[:book_id])
   comment = current_user.book_comments.new(book_comment_params)
   comment.book_id = book.id
   comment.save
   @books=Book.find(params[:book_id])
   @book_comment = BookComment.new
end

 def destroy
  @books=Book.find(params[:book_id])
  @book_comment=BookComment.find_by(id: params[:id], book_id: params[:book_id])
  @book_comment.destroy
  @book_comment = BookComment.new
 end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @book = Book.new
        @books = Book.all
        @book_comment = BookComment.new
    end

    def show
        @books = Book.all
        @book = Book.find(params[:id])
        @book_new = Book.new
        @book_comment = BookComment.new
    end

    def edit
        @book = Book.find(params[:id])
        if current_user.id == @book.user.id
        else
            redirect_to books_path
        end

    end

    def create
        @books = Book.all
        @book = Book.new(book_params)
        @book.user_id=current_user.id
        if @book.save
        flash[:notice] = "successfully"
            redirect_to book_path(@book)
        else
            render :index
        end
    end

      def destroy
         book = Book.find(params[:id])
         book.destroy
         redirect_to '/books'
      end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
        flash[:notice] = "successfully"
        redirect_to book_path(@book.id)
        else
        render :edit
        end
    end

    private
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
    
    def about
    end    
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_current_user, {only: [:edit, :update]}
  def show
     @user = User.find(params[:id])
     #@books = @user.books
     @book = Book.new
     @book_comment = BookComment.new
     @books = @user.books.reverse_order
     @following_users = @user.followings
     @follower_users = @user.followers
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "successfully"
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end
  def follows
  user = User.find(params[:id])
  @users = user.followings.reverse_order
  end

  def followers
  user = User.find(params[:id])
  @users = user.followers.reverse_order
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_current_user
    if current_user.id != params[:id].to_i
    flash[:notice] = "Welcome! You have signed up successfully."
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
 <%= form_with model: [@book, @book_comment] ,local: false do |f| %>
          <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>

        <% end %>

app/views/book_comments/create.js.erb
$("#comments-area").html("<%= j(render 'book_comments/comment', books: @books,book_comment: @book_comment) %>")

app/views/books/edit.html.erb
<div class="container">
<div class="row">
<div class="col-md-3">
<div class="col-md-8 offset-md-1">
  <h1>Editing Book</h1>
  
  <%= form_with model: @book do |f| %>
  <div>
    <h4>Title</h4>
  
    <%= f.text_field :title %>
  
    <h4>Body</h4>
    <%= f.text_area :body %>
  
  <%#= link_to "/book", show_book_path(@book.id) %>
  <%= link_to 'Show', book_path(@book.id) %> |
   <%= link_to 'Back', books_path %>
       </div>
      <%= f.submit %>
  <% end %>
  
  <%= flash[:notice] %>
  
   <% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
</div>
</div>
</div>

app/views/books/index.html.erb
<headr>
    <span>Bookers</span>
</headr>

<body>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<div class="col-md-8 offset-md-1">

    <h2>Users info</h2>

    <p><%= image_tag current_user.get_profile_image(100,100) %></p>


      <table>
    <tbody><tr></tr>
    <tr>
  	  <th>name</th>
  	  <th><%=current_user.name %></th>
    </tr>
    <tr>
  	  <th>introduction</th>
  	  <th><%=current_user.introduction %></th>
    </tr>
  </tbody></table>

  <%= link_to edit_user_path(current_user.id) ,{class:"btn btn-outline-secondary btn-block"} do %>
  <i class="fas fa-user-cog"></i>
  <%end%>

   <%= flash[:notice] %>

   <% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul
  <% end %>

  <h4>New book</h4>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <%= f.submit "Create Book"%>

  <%end%>

     <table>
  <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <table>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <td>
          <!--いいね機能-->
          <td id="favorite_buttons_<%= @book.id %>">
        <%= render "favorites/favorite", book: book %>
        </td>
        <!--<td id="favorite_buttons_<%#= book.id %>">
          <%#= render "favorites/favorite", book: book %>-->
        </td>
        <td>コメント件数：<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  </div>
  </div>
  </div>
  </div>
    </body>

<footer></footer>

app/views/books/show.html.erb
<headr></headr>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <p>投稿ユーザー画像：<%= image_tag current_user.get_profile_image(100,100) %></p>
      <table>
        <tbody><tr></tr>
        <tr>
      	  <th>name</th>
      	  <th><%=@book.user.name %></th>
        </tr>
        <tr>
      	  <th>introduction</th>
      	  <th><%=@book.user.introduction %></th>
        </tr>
      </tbody></table>

      <%= link_to edit_user_path(@book.user.id) ,{class:"btn btn-outline-secondary btn-block"} do %>
      <i class="fas fa-user-cog"></i>
      <%end%>

      <h4>New book</h4>
      <%= form_with model: @book_new do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>

        <h4>Opinion</h4>
        <%= f.text_area :body %>

        <%= f.submit "Create Book"%>

      <%end%>
    </div>
    <div class="col-md-8 offset-md-1">
      <h4>Book detail</h4>
      <table>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= image_tag 'no_image.jpg' %>
            </td>
            <td>
              <%= link_to @book.user.name, user_path(@book.user.id) %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book.id) %>
            </td>
            <td>
              <%=@book.body %>
            </td>
          <!--</tr>-->
          <!--<tr>-->
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path(@book.id) %>
                <%= link_to "Destroy", book_path(@book), method: :delete %>
              <% end %>
           </td>
            <td id="favorite_buttons_<%= @book.id %>">
              <%= render "favorites/favorite", book: @book %>
            </td>
            <td>
              コメント件数：<%=@book.book_comments.count %>
            </td>
          </tr>
        </tbody>
      </table>
     <div id="comments-area"><%= render "book_comments/comment",books: @books,book_comment: @book_comment %></div>
      <% @book.book_comments.each do |book_comment| %>
                <div><%= image_tag book_comment.user.get_profile_image(100,100) %>
                <%= book_comment.user.name %>
                <%= book_comment.comment %>
                <%= link_to "Destroy", book_path(@book), method: :delete %>
              </div><% end %>
    </div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    ♥<%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    ♡<%= book.favorites.count %> いいね
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/homes/about.html.erb
<h1>Welcome to <i class="fas fa-book">bookers!</h1>
<head></head>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <div class="col-md-8 offset-md-1">
<h1>welcome to <i class="fas fa-book"></i>bookers!!</h1>
<p>In <i class="fas fa-book"></i>Bookers</p>
<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>


 <div class="row">
<%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
 </div>
  <div class="row">
<%= link_to "Sign up", new_user_registration_path, {class:"btn btn-success btn-sm btn-block sign_up"} %>
  </div>
</div>
</div>
</div>
</div

app/views/relationships/followers.html.erb
<h1>Relationships#followers</h1>
<p>Find me in app/views/relationships/followers.html.erb</p>

 if users.exists? %>
  <% users.each do |user| %>
    <table>
      <thead>
        <tr>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h1>Relationships#followings</h1>
<p>Find me in app/views/relationships/followings.html.erb</p>

 if users.exists? %>
  <% users.each do |user| %>
    <table>
      <thead>
        <tr>
          <th>name</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/searches/search.html.erb
<h2>Results index</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/users/edit.html.erb
<h1>User info</h1>

   <%= flash[:notice] %>

 <% if @user.errors.any? %>
  <%= @user.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



 <%= form_with model: @user do |f| %>
  <h4>name</h4>
  <%= f.text_field :name %>

  <h4>image</h4>
  <h4>  <%= f.file_field :profile_image, accept: "image/*" %></h4>

  <h4>introduction</h4>
  <%= f.text_area :introduction %>

   <%= f.submit %>
   <%end%>

app/views/users/followers.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<div class="col-md-8 offset-md-1">
   <h2>Users info</h2>
  
    <p><%= image_tag current_user.get_profile_image(100,100) %></p>
  
  
      <table>
    <tbody><tr></tr>
    <tr>
  	  <th>name</th>
  	  <th><%=current_user.name %></th>
    </tr>
    <tr>
  	  <th>introduction</th>
  	  <th><%=current_user.introduction %></th>
    </tr>
  </tbody></table>
  
  <%= link_to edit_user_path(current_user.id) ,{class:"btn btn-outline-secondary btn-block"} do %>
  <i class="fas fa-user-cog"></i>
  <%end%>
  
  <h4>New book</h4>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
  
    <h4>Opinion</h4>
    <%= f.text_area :body %>
  
    <%= f.submit "Create Book"%>
  
  <%end%>
  
  
     <table>
  <thead>
      <tr>
        <th></th>
        <th>imege</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
     <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= image_tag 'no_image.jpg' %></td>
          <td><%=user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
    <% end %>
  
  </div>
  </div>
  </div>
  </div>
    </tbody>

app/views/users/follows.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<div class="col-md-8 offset-md-1">
   <h2>Users info</h2>
  
    <p><%= image_tag current_user.get_profile_image(100,100) %></p>
  
  
      <table>
    <tbody><tr></tr>
    <tr>
  	  <th>name</th>
  	  <th><%=current_user.name %></th>
    </tr>
    <tr>
  	  <th>introduction</th>
  	  <th><%=current_user.introduction %></th>
    </tr>
  </tbody></table>
  
  <%= link_to edit_user_path(current_user.id) ,{class:"btn btn-outline-secondary btn-block"} do %>
  <i class="fas fa-user-cog"></i>
  <%end%>
  
  <h4>New book</h4>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
  
    <h4>Opinion</h4>
    <%= f.text_area :body %>
  
    <%= f.submit "Create Book"%>
  
  <%end%>
  
  
     <table>
  <thead>
      <tr>
        <th></th>
        <th>imege</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
     <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= image_tag 'no_image.jpg' %></td>
          <td><%=user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
    <% end %>
  
  </div>
  </div>
  </div>
  </div>
    </tbody>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<div class="col-md-8 offset-md-1">
   <h2>Users info</h2>
  
    <p><%= image_tag current_user.get_profile_image(100,100) %></p>
  
  
      <table>
    <tbody><tr></tr>
    <tr>
  	  <th>name</th>
  	  <th><%=current_user.name %></th>
    </tr>
    <tr>
  	  <th>introduction</th>
  	  <th><%=current_user.introduction %></th>
    </tr>
  </tbody></table>
  
  <%= link_to edit_user_path(current_user.id) ,{class:"btn btn-outline-secondary btn-block"} do %>
  <i class="fas fa-user-cog"></i>
  <%end%>
  
  <h4>New book</h4>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
  
    <h4>Opinion</h4>
    <%= f.text_area :body %>
  
    <%= f.submit "Create Book"%>
  
  <%end%>
  
  
     <table>
  <thead>
      <tr>
        <th></th>
        <th>imege</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
     <tbody>
    <% @users.each do |user| %>
        <tr>
          <td><%= image_tag 'no_image.jpg' %></td>
          <td><%=user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
    <% end %>
  
  </div>
  </div>
  </div>
  </div>
    </tbody>

app/views/users/show.html.erb
<%= flash[:notice] %>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<div class="col-md-8 offset-md-1">
  <h2>Users info</h2>
  <p><%= image_tag current_user.get_profile_image(100,100) %></p>
    <table>
    <tbody><tr></tr>
    <tr>
  	  <th>name</th>
  	  <th><%=@user.name %></th>
    </tr>
    <tr>
  	  <th>introduction</th>
  	  <th><%=@user.introduction %></th>
    </tr>
  </tbody></table>


  <div class="row">
  <%= link_to edit_user_path(@user.id) ,{class:"btn btn-outline-secondary btn-block"} do %>
  <i class="fas fa-user-cog"></i>
  <%end%>
  </div>


  <% if @book.errors.any? %>
    <%= @book.errors.count %> errors prohibited this book from being saved:
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul
  <% end %>

  <h4>New book</h4>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <%= f.submit "Create Book"%>

  <%end%>


  <table>
   <thead>
     <h1>New book</h1>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>

         <tbody>
      <% @books.each do |book| %>
          <tr>
          <td>
              <%= link_to user_path(book.user.id) do %>
              <%= image_tag 'no_image.jpg' %>
                  <%end%>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%=book.body %></td>
           <td><%= "#{book.book_comments.count} コメント" %></td>
          </tr>
      <% end %>
        </tbody>
        </table>
        <p class="d-flex justify-content-end">
   <% if user_signed_in? && @user == current_user %>
   <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn-sm btn-success" %>
   <% end %>
   <% if current_user != @user %>
   <% if current_user.following?(@user) %>
   <%= link_to 'フォロー外す', user_relationships_path(@user.id), method: :delete, class: "btn-sm btn-danger" %>
   <% else %>
   <%= link_to 'フォローする', user_relationships_path(@user.id), method: :POST, class:"btn-sm btn-success" %>
   <% end %>
 </p>
 <% end %>
 <div class="ml-3 mb-3 card w-100">
   <div class="d-flex">
     <%= image_tag @user.profile_image, size: '100x100', class: "mb-3 mt-3 ml-3 profile-img" %>
     <h4 class="ml-5 m-3"><%= @user.name %></h4>
   </div>
   <div class="d-flex">
     <%= link_to follows_user_path(@user) do %>
     <h6>フォロー<%= @following_users.count %></h6>
     <% end %>&nbsp;&nbsp;
     <%= link_to followers_user_path(@user) do %>
     <h6>フォロワー<%= @follower_users.count %></h6>
     <% end %>
   </div>
 </div>
 <div class=" row justify-content-center">
・・・
    </div>
    </div>
    </div>
    </div>