config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  get 'home/about' => 'homes#about'
  get "search" => "searches#search"


  resources :users, only: [:show, :edit, :update, :index]
  resources :books, only: [:create, :index, :show, :destroy, :edit, :updatey] do
  resource :favorites, only: [:create, :destroy]
  resources :book_comments, only: [:create, :destroy]
    end

  resources :users, only:[:index, :show, :edit, :update] do
  member do
  get :follows, :followers
      end
  resource :relationships, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
     belongs_to :user
     belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :authenticate_user!, except: [:top, :about]
 before_action :configure_permitted_parameters, if: :devise_controller?

   def after_sign_in_path_for(resource)
    user_path(current_user.id)
   end

   def after_sign_out_path_for(resource)
    root_path
   end

   private

   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
   end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

def create
   book = Book.find(params[:book_id])
   comment = current_user.book_comments.new(book_comment_params)
   comment.book_id = book.id
   comment.save
   @books=Book.find(params[:book_id])
   @book_comment = BookComment.new
end

 def destroy
  @books=Book.find(params[:book_id])
  @book_comment=BookComment.find_by(id: params[:id], book_id: params[:book_id])
  @book_comment.destroy
  @book_comment = BookComment.new
 end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @book = Book.new
        @books = Book.all
        @book_comment = BookComment.new
    end

    def show
        @books = Book.all
        @book = Book.find(params[:id])
        @book_new = Book.new
        @book_comment = BookComment.new
    end

    def edit
        @book = Book.find(params[:id])
        if current_user.id == @book.user.id
        else
            redirect_to books_path
        end

    end

    def create
        @books = Book.all
        @book = Book.new(book_params)
        @book.user_id=current_user.id
        if @book.save
        flash[:notice] = "successfully"
            redirect_to book_path(@book)
        else
            render :index
        end
    end

      def destroy
         book = Book.find(params[:id])
         book.destroy
         redirect_to '/books'
      end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
        flash[:notice] = "successfully"
        redirect_to book_path(@book.id)
        else
        render :edit
        end
    end

    private
    def book_params
        params.require(:book).permit(:title, :body)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
    
    def about
    end    
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_current_user, {only: [:edit, :update]}
  def show
     @user = User.find(params[:id])
     #@books = @user.books
     @book = Book.new
     @book_comment = BookComment.new
     @books = @user.books.reverse_order
     @following_users = @user.followings
     @follower_users = @user.followers
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "successfully"
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end
  def follows
  user = User.find(params[:id])
  @users = user.followings.reverse_order
  end

  def followers
  user = User.find(params[:id])
  @users = user.followers.reverse_order
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def ensure_current_user
    if current_user.id != params[:id].to_i
    flash[:notice] = "Welcome! You have signed up successfully."
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



      <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/">
          <span>Bookers</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if user_signed_in? %>
                <li>
                <%= link_to user_path(current_user.id) do %>
                <i class="fas fa-home"></i>Home
                <%end%>
                </li>
                <li>
              <%= link_to users_path do %>
               <i class="fas fa-users"></i>Users
               <%end%>
             </li>
              <li>
              <%= link_to books_path do %>
              <i class="fas fa-book-open"></i>Books
              <%end%>
             </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                 <i class="fas fa-sign-out-alt"></i>Log out
                 <%end%>
              </li>
            <% else %>
            <li>
                <%= link_to root_path do %>
                <i class="fas fa-home"></i>Home
                <%end%>
              </li>
            <li>
                <%= link_to home_about_path do %>
                 <i class="fas fa-link"></i>About
                 <%end%>
              </li>
              <li>
                <%= link_to new_user_registration_path do %>
                   <i class="fas fa-user-plus"></i>Sign up
                   <%end%>
              </li>
              <li>
                <%= link_to new_user_session_path do %>
                <i class="fas fa-sign-in-alt"></i>Log in
                <%end%>
              </li>
               </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Book']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>
  </header>
  <%= flash[:notice] %>
    <%= yield %>

  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
 </body>
</html>